const APP = Object.freeze({
  SPREADSHEET_ID: '1kbx3EkS9NvGJRP9m9lbgLKKj2L_zrxi_ENMSav_lwIc',
  TZ: 'Europe/Rome',
  SHEETS: Object.freeze({
    CALENDAR: 'Calendario',
    CHECKLIST: '_CHECKLIST',
    EXPENSES: '_SPESE',
    PARTICIPANTS: '_PARTECIPANTI',
    PEOPLE: '_ANAGRAFICA',
    DOCUMENTS: '_DOCUMENTI',
    COMMUNICATIONS: '_COMUNICAZIONI',
    CHECKLIST_CONFIG: '_CONFIG_CHECKLIST',
    CEB_CONFIG: '_CONFIG_CEB',
    EVENT_TYPE_CONFIG: '_CONFIG_TIPI_EVENTO',
    COMMITMENT_CONFIG: '_CONFIG_IMPEGNI',
    CONFIG: '_CONFIG',
    EVENT_META: '_EVENTI_META',
    REFUND_CONFIG: '_CONFIG_RIMBORSI',
    LOG: '_LOG'
  }),
  CALENDAR_HEADERS: Object.freeze({
    ID: 'ID EVENTO',
    START: 'DATA INIZIO',
    END: 'DATA FINE',
    TYPE: 'TIPO',
    CLASS: 'CLASSE',
    EVENT: 'NOTE EVENTO',
    LOCATION: "LOCALITA'",
    ZONE: 'ZONA',
    CLUB: 'CIRCOLO',
    TECHNICIANS: 'TECNICI',
    LODGING: 'ALLOGGIO / STRUTTURA',
    COMMITMENT: 'IMPEGNO',
    CHECKLIST: 'CHECKLIST',
    NEXT_ACTION: 'DA COMPLETARE',
    DEADLINE: 'SCADENZA',
    BUDGET: 'PREVENTIVO',
    ACTUAL: 'CONSUNTIVO',
    TO_PAY: 'DA SALDARE',
    FOLDER: 'CARTELLA',
    NOTES: 'NOTE'
  }),
  COLORS: Object.freeze({
    OK: '#188038',
    WARN: '#f9ab00',
    LATE: '#d93025',
    MUTED: '#5f6368'
  })
});