const ACTIVITY_V13=Object.freeze({VISIBLE:7,WIDTH:16,TYPE:8,OBJECTIVE_ID:9,TASK_ID:10,OBJECTIVE_ORDER:11,STEP_ORDER:12,COLOR:13,AUTO_DUE:14,PREVIOUS_ID:15,COMPLETED_AT:16});

function prepareEventSheetForSelectedEventV13(){
  const event=selectedEvent_(),eventId=ensureEventId_(event),folder=createWorkFolderForEvent_(eventId,event,event._row);let child=getLinkedEventSheet_(event),created=false;
  if(!child){const copy=DriveApp.getFileById(EVENT_SHEET.TEMPLATE_ID).makeCopy(buildEventSheetName_(event),DriveApp.getFolderById(folder.folderId));child=SpreadsheetApp.openById(copy.getId());child.setSpreadsheetLocale('it_IT');child.setSpreadsheetTimeZone(APP.TZ);created=true;}
  if(!isCurrentEventSheet_(child))throw new Error('La Scheda evento collegata non usa il modello corrente.');validateEventSheetIdentity_(child,eventId);writeEventMeta_(child,eventId,event,folder.folderId);applyEventCommitment_(child,event);
  ensureObjectivesBackendV13_();if(!getObjectivesForEvent_(eventId).length)generateChecklistForEvent_(eventId,event);
  if(created||isObjectiveActivitySheetV13_(child))writeObjectivesToEventSheetV13_(eventId,child);
  writeCurrentParticipantsToEventSheet_(eventId,child);populateCurrentTechnicians_(child,event);setEventSheetLink_(event._row,child.getUrl());refreshCalendarActivityDashboardForEvent_(eventId);SpreadsheetApp.flush();SpreadsheetApp.getActive().toast(created?'Scheda evento creata':'Dati evento aggiornati','Scheda evento',5);return{created:created,id:child.getId(),url:child.getUrl()};
}
function isObjectiveActivitySheetV13_(child){const sh=child&&child.getSheetByName(EVENT_SHEET.SHEETS.TASKS);return !!sh&&normalize_(sh.getRange('A1').getDisplayValue())==='OBIETTIVO'&&normalize_(sh.getRange('C1').getDisplayValue())==='ATTIVITA';}
function writeObjectivesToEventSheetV13_(eventId,child){
  const sheet=child.getSheetByName(EVENT_SHEET.SHEETS.TASKS);if(!sheet)throw new Error('Foglio Attività non trovato.');const objectives=getObjectivesForEvent_(eventId),rows=[];
  objectives.forEach(o=>{rows.push([o.name,o.dueDate||'','','','',o.status,'','OBIETTIVO',o.id,'',o.order||'','',o.color||'#D9EAF7',false,'','']);o.tasks.forEach(t=>rows.push(['','',t.task||'',t.dueDate||'',['FATTO','COMPLETATA'].includes(normalize_(t.status)),t.status||'IN ATTESA',t.note||'','TASK',o.id,t.id||'',o.order||'',t.stepOrder||'',o.color||'',t.autoDue===true,t.previousTaskId||t.dependencyId||'',t.completedAt||'']));});
  const max=Math.min(500,sheet.getMaxRows());if(max>=2)sheet.getRange(2,1,max-1,ACTIVITY_V13.WIDTH).clearContent().clearFormat();sheet.getRange(1,1,1,ACTIVITY_V13.WIDTH).setValues([['OBIETTIVO','SCADENZA OBIETTIVO','ATTIVITÀ','SCADENZA','FATTO','STATO','NOTE','TIPO RIGA','ID OBIETTIVO','ID TASK','ORDINE OBIETTIVO','ORDINE STEP','COLORE','SCADENZA AUTOMATICA','ID TASK PRECEDENTE','DATA COMPLETAMENTO']]);
  if(rows.length)sheet.getRange(2,1,rows.length,ACTIVITY_V13.WIDTH).setValues(rows);sheet.setFrozenRows(1);sheet.setColumnWidth(1,210);sheet.setColumnWidth(2,125);sheet.setColumnWidth(3,310);sheet.setColumnWidth(4,105);sheet.setColumnWidth(5,60);sheet.setColumnWidth(6,110);sheet.setColumnWidth(7,260);sheet.getRange(1,1,1,7).setFontWeight('bold').setHorizontalAlignment('center').setVerticalAlignment('middle').setWrap(true);sheet.getRange(2,1,Math.max(rows.length,1),7).setVerticalAlignment('middle').setWrap(true);
  if(rows.length){sheet.getRange(2,5,rows.length,1).insertCheckboxes();objectives.forEach(o=>{const idx=rows.findIndex(r=>r[7]==='OBIETTIVO'&&r[8]===o.id);if(idx<0)return;const headerRow=idx+2;sheet.getRange(headerRow,1,1,7).setBackground(o.color||'#D9EAF7').setFontWeight('bold');sheet.getRange(headerRow,5).clearDataValidations().clearContent();const count=o.tasks.length;if(count>0){try{sheet.getRange(headerRow+1,1,count,1).shiftRowGroupDepth(1);}catch(e){console.log('Gruppo righe: '+e.message);}}});}
  sheet.hideColumns(8,9);sheet.getRange(2,2,Math.max(rows.length,1),1).setNumberFormat('dd/MM/yyyy');sheet.getRange(2,4,Math.max(rows.length,1),1).setNumberFormat('dd/MM/yyyy');
}

function syncSelectedEventSheetToCalendarV13(){const event=selectedEvent_(),eventId=ensureEventId_(event),child=getLinkedEventSheet_(event);if(!child)throw new Error('Nessuna Scheda evento collegata.');syncObjectiveEventSheetV13_(child,eventId);SpreadsheetApp.getActive().toast('Scheda sincronizzata','Attività',4);}
function syncAllEventSheetsToCalendarV13(){const cal=sh_(APP.SHEETS.CALENDAR),map=headerMap_(cal),last=cal.getLastRow();let synced=0,skipped=0;for(let row=2;row<=last;row++){const eventId=String(cal.getRange(row,map[APP.CALENDAR_HEADERS.ID]).getDisplayValue()||'').trim();if(!eventId)continue;const event={_row:row};Object.keys(map).forEach(h=>event[h]=cal.getRange(row,map[h]).getValue());const child=getLinkedEventSheet_(event);if(!child){skipped++;continue;}if(!isObjectiveActivitySheetV13_(child)){skipped++;continue;}syncObjectiveEventSheetV13_(child,eventId);synced++;}SpreadsheetApp.getUi().alert('Sincronizzazione attività','Schede V13 sincronizzate: '+synced+'\nSchede legacy ignorate: '+skipped,SpreadsheetApp.getUi().ButtonSet.OK);}
function syncObjectiveEventSheetV13_(child,eventId){
  validateEventSheetIdentity_(child,eventId);const local=child.getSheetByName(EVENT_SHEET.SHEETS.TASKS);if(!local||!isObjectiveActivitySheetV13_(child))throw new Error('La Scheda non usa ancora il layout Obiettivi V13.');ensureObjectivesBackendV13_();const objectiveBackend=sh_(APP.SHEETS.OBJECTIVES),taskBackend=sh_(APP.SHEETS.CHECKLIST),oldObjs=objectiveBackend.getDataRange().getValues(),oldTasks=taskBackend.getDataRange().getValues(),objById={},taskById={};oldObjs.slice(1).forEach(r=>{if(String(r[1])===String(eventId)&&r[0])objById[String(r[0])]=r;});oldTasks.slice(1).forEach(r=>{if(String(r[1])===String(eventId)&&r[0])taskById[String(r[0])]=r;});
  const last=Math.min(500,Math.max(local.getLastRow(),2)),values=local.getRange(2,1,last-1,ACTIVITY_V13.WIDTH).getValues(),now=new Date(),objs=[],tasks=[];values.forEach((r,i)=>{if(normalize_(r[7])!=='OBIETTIVO'||!String(r[0]||'').trim())return;let id=String(r[8]||'').trim();if(!id){id='OBJ-'+Utilities.getUuid();local.getRange(i+2,9).setValue(id);}const old=objById[id]||[];objs.push([id,eventId,String(r[0]).trim(),String(r[12]||old[3]||objectiveColorForIndex_(objs.length)),r[1] instanceof Date?r[1]:'',Number(r[10]||old[5]||((objs.length+1)*10)),old[6]||'SCHEDA EVENTO',old[7]||'',old[8]||'',old[9]||now,now]);});
  values.forEach((r,i)=>{if(normalize_(r[7])!=='TASK'||!String(r[2]||'').trim()||!r[8])return;let id=String(r[9]||'').trim();if(!id){id='TASK-'+Utilities.getUuid();local.getRange(i+2,10).setValue(id);}const old=taskById[id]||[],done=r[4]===true,status=done?'FATTO':(normalize_(r[5])||'IN ATTESA'),oid=String(r[8]),step=Number(r[11]||10),objOrder=Number(r[10]||10),prev=String(r[14]||'').trim(),completed=done?(r[15] instanceof Date?r[15]:(old[11] instanceof Date?old[11]:now)):'';tasks.push([id,eventId,objOrder*100+step,String(r[2]).trim(),old[4]||'ALTRO',r[3] instanceof Date?r[3]:'',status,old[7]||'',old[8]||'SCHEDA EVENTO',old[9]||'',String(r[6]||'').trim(),completed,now,old[13]||tasks.length+1,prev,prev&&status!=='FATTO'?'DIPENDENZA':'',oid,step,r[13]===true,prev]);});
  replaceCentralRowsForEvent_(objectiveBackend,eventId,2,objs,11);replaceCentralRowsForEvent_(taskBackend,eventId,2,tasks,20);syncChecklistLocksForEvent_(eventId);refreshCalendarActivityDashboardForEvent_(eventId);SpreadsheetApp.flush();return{objectives:objs.length,tasks:tasks.length};
}
